services:
  loadbalance:
    image: nginx:1.25.2-alpine
    ports:
      - "8080:80"
    container_name: loadbalance
  node1:
    image: nginx:1.25.2-alpine
    container_name: node1
    volumes:
      - "./build:/usr/share/nginx/html"
  node2:
    image: nginx:1.25.2-alpine
    container_name: node2
    volumes:
      - "./build:/usr/share/nginx/html"
  node3:
    image: nginx:1.25.2-alpine
    container_name: node3
    volumes:
      - "./build:/usr/share/nginx/html"